### ISSUE TITLE
Proposal Feedback

### ISSUE THREAD

**Issue by trevoruptain** [corina-s/goPup#1]
Your proposal is very well written. The only thing missing is your implementation timeline - please see the [sample proposal](https://open.appacademy.io/learn/swe-online/swe-online---docker-graphql-project/sample-proposal) for an example of this - we are looking for a detailed work breakdown for each team member.

**Comment by jessewarren-aa** [comment]
Resolved. Thanks for the feedback, let us know if further changes are necessary!
